# Generated by Django 4.2.5 on 2024-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
