# Generated by Django 4.2.5 on 2024-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_numero_de_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_de_telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
