# Generated by Django 4.2.5 on 2024-02-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_customuser_numero_de_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_de_telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
