# Generated by Django 4.2.5 on 2024-02-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_customuser_numero_de_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='numero_de_telefono',
        ),
    ]
