# Generated by Django 4.2.5 on 2024-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin'), ('user', 'User'), ('worker', 'Worker')], max_length=10),
        ),
    ]
