# Generated by Django 4.2.5 on 2024-02-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nivel_dano_capo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('nivel_dano_paragolpes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('nivel_dano_lateral_izq', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('nivel_dano_lateral_der', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('nivel_dano_techo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('nivel_dano_atras', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
