# Generated by Django 4.2.5 on 2024-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0004_incidencia_contacto_testigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_hora_siniestro',
            field=models.DateTimeField(verbose_name='Fecha y hora del siniestro'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='llamada_policia',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default=False, max_length=2, verbose_name='¿Se llamó a la policía?'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='marca_modelo',
            field=models.CharField(max_length=50, verbose_name='Marca y Modelo'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='matricula',
            field=models.CharField(max_length=20, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='nombre_asegurado',
            field=models.CharField(max_length=100, verbose_name='Nombre y Apellidos del asegurado'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='telefono_movil',
            field=models.CharField(max_length=20, verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_aparcamiento',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default=False, max_length=2, verbose_name='Tipo de Aparcamiento'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='ubicacion_siniestro',
            field=models.CharField(max_length=255, verbose_name='Ubicación del siniestro'),
        ),
    ]
