# Generated by Django 4.2.5 on 2024-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0005_alter_incidencia_fecha_hora_siniestro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_hora_siniestro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del siniestro'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='llamada_policia',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default=False, max_length=2, null=True, verbose_name='¿Se llamó a la policía?'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca y Modelo'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='nombre_asegurado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre y Apellidos del asegurado'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_aparcamiento',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Tipo de Aparcamiento'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='ubicacion_siniestro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación del siniestro'),
        ),
    ]
