# Generated by Django 4.2.5 on 2024-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0009_alter_incidencia_fecha_hora_siniestro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='email'),
        ),
    ]
