# Generated by Django 4.2.5 on 2024-03-19 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_visualization', '0010_incidencia_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_poliza', models.CharField(max_length=50, verbose_name='Tipo de Póliza')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones de la Póliza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFraudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidente', models.DateField(verbose_name='Fecha del Incidente')),
                ('descripcion', models.TextField(verbose_name='Descripción del Fraude')),
                ('estado_investigacion', models.CharField(default='En proceso', max_length=100, verbose_name='Estado de la Investigación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
