# Generated by Django 4.2.5 on 2024-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0011_poliza_historialfraudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
