# Generated by Django 4.2.5 on 2024-04-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_visualization', '0012_incidencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaRevisada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia_id', models.IntegerField()),
                ('respuestas_json', models.TextField()),
                ('recomendaciones_json', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
