# Generated by Django 3.2.12 on 2024-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0013_incidenciarevisada'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='anos_carnet',
            field=models.IntegerField(default='2', verbose_name='Años de Carnet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poliza',
            name='edad_conductor',
            field=models.IntegerField(default='2', verbose_name='Edad del Conductor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poliza',
            name='importe_poliza',
            field=models.DecimalField(decimal_places=2, default='23.21', max_digits=10, verbose_name='Importe de la Póliza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poliza',
            name='puntos_carnet',
            field=models.IntegerField(default='2', verbose_name='Puntos del Carnet'),
            preserve_default=False,
        ),
    ]
