# Generated by Django 3.2.12 on 2024-04-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_visualization', '0014_auto_20240412_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='email')),
                ('descripcion', models.TextField()),
                ('fecha_hora_siniestro', models.DateTimeField(null=True, verbose_name='Fecha y hora del siniestro')),
                ('ubicacion_siniestro', models.CharField(max_length=255, null=True, verbose_name='Ubicación del siniestro')),
                ('tipo_aparcamiento', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='Tipo de Aparcamiento')),
                ('matricula', models.CharField(max_length=20, null=True, verbose_name='Matrícula')),
                ('marca_modelo', models.CharField(max_length=50, null=True, verbose_name='Marca y Modelo')),
                ('nombre_asegurado', models.CharField(max_length=100, null=True, verbose_name='Nombre y Apellidos del asegurado')),
                ('telefono_movil', models.CharField(max_length=20, null=True, verbose_name='Teléfono móvil')),
                ('vehiculos_propiedades_involucrados', models.TextField(blank=True, null=True, verbose_name='Vehículos o propiedades involucrados')),
                ('testigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Testigo')),
                ('contacto_testigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto del testigo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
