# Generated by Django 3.2.12 on 2024-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0015_historialincidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialfraudes',
            name='estado_investigacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('datos_insuficientes', 'Datos Insuficientes'), ('en_espera_de_documentacion', 'En Espera de Documentación'), ('fraude_confirmado', 'Fraude Confirmado'), ('sin_fraude', 'Sin Fraude'), ('fraude_sospechoso', 'Fraude Sospechoso'), ('archivado', 'Archivado'), ('revision_externa', 'Revisión Externa'), ('en_litigio', 'En Litigio')], default='pendiente', max_length=50, verbose_name='Estado de la Investigación'),
        ),
    ]
