# Generated by Django 3.2.12 on 2024-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_visualization', '0016_alter_historialfraudes_estado_investigacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialfraudes',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Fraude'),
        ),
        migrations.AlterField(
            model_name='historialfraudes',
            name='fecha_incidente',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Incidente'),
        ),
    ]
